# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_contadorvisitas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contadorVisitas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
